config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root to: 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save!
      flash[:notice] = 'Congratulations! We have a new kitten here!'
      redirect_to @kitten
    else
      flash[:alert] = "Check again, we don't want to deal with stupid mistakes here"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update!(kitten_params)
      flash[:notice] = 'Congratulations! Your kitten has been updated!'
      redirect_to @kitten
    else
      flash[:alert] = 'Check again, if you have to make mistakes, might as well leave it as it is'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    if @kitten.destroy
      flash[:notice] = 'Goodbye kitty'
      redirect_to root_path
    else
      flash[:alert] = 'The kitten resisted your attempt to deletion!'
      render @kitten, status: :unprocessable_entity
    end
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<h1>Modify the kitten</h1>
If you want to change some of the details of your kitten, this is the place!
<br /><br />
<%= render "layouts/kitten_form" do %>
  <%= hidden_field_tag 'id', @kitten.id %>
<% end %>
<br /><br />
<%= form_with model: @kitten, url: kittens_path, method: :delete  do |form| %>
  <%= form.hidden_field :id, :value => @kitten.id %>
  <%= form.submit "Delete" %>
<% end %>

<%= render "layouts/flash" %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<br />
<% if @kittens.any? %>
  <ul>
    <% @kittens.each do |k| %>
      <div>
        <%= link_to "Kitten number #{k.id}", "kittens/#{k.id}" %><br />
        Name: <%= k.name %><br />
        Age: <%= k.age %><br />
        Cuteness: <%= k.cuteness %><br />
        Softness: <%= k.softness %><br />
        <%= form_with model: @kitten, url: "kittens/#{k.id}", method: :delete  do |form| %>
          <%= form.hidden_field :id, :value => k.id %>
          <%= form.submit "Delete" %>
        <% end %>
        <br />
        <%= link_to "Edit", edit_kitten_path(k.id) %>
        <br /><br />
      </div>
    <% end %>
  </ul>
<% else %>
  No kittens :(
<% end %>
<br /><br />
<%= link_to "New Kitten", new_kitten_path %>

<%= render "layouts/flash" %>

app/views/kittens/new.html.erb
<h1>A new kitten!</h1>
Tell us about this kitten!
<br /><br />
<%= render "layouts/kitten_form" %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name.capitalize %></h1>

Age: <%= @kitten.age %><br />
Cuteness: <%= @kitten.cuteness %><br />
Softness: <%= @kitten.softness %><br /><br />

<%= form_with model: @kitten, url: kittens_path(@kitten.id), method: :delete  do |form| %>
  <%= form.hidden_field :id, :value => @kitten.id %>
  <%= form.submit "Delete" %>
<% end %>

<br /><br />

<%= link_to "Go back", root_path %>

<%= render "layouts/flash" %>

app/views/layouts/_flash.html.erb
<% if flash[:alert] %>
  <br />
  <br />
  <div class="alert"><%= flash[:alert] %></div>
<% end %>
<% if flash[:notice] %>
  <br />
  <br />
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/layouts/_kitten_form.html.erb
<%= form_with model: @kitten do |f| %>
  <%= f.label :name, "Name: " %><br />
  <%= f.text_field :name %><br /><br />
  <%= f.label :age, "Age: " %><br />
  <%= f.number_field :age %><br /><br />
  <%= f.label :cuteness, "Cuteness: " %>
  <%= f.select(:cuteness, options_for_select([*1..10])) %><br /><br />
  <%= f.label :softness, "Softness: " %>
  <%= f.select(:softness, options_for_select([*1..10])) %><br /><br />
  <%= yield %>
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>